baseURL = 'https://www.forcepushrevert.com/'
languageCode = 'en-us'
title = 'Force Push Revert'
theme = "Mainroad"

[Author]
  name = "Tyler Finethy"
  bio = "Software Engineer @ RStudio, PBC"

[Params]
  description = "Force Push Revert Blog"
  copyright = "Tyler Finethy"
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = [] # Order of post meta information
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  widgets = ["social"]

[Params.widgets.social]
  twitter = "tylfin"
  linkedin = "tylfin"
  github = "tylfin"
  email = "tylfinz@gmail.com"
